/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioIdRouteImport } from './routes/studio.$id'
import { Route as StudioVaultRouteImport } from './routes/studio.vault'
import { Route as VisitReferenceRouteImport } from './routes/visit.$reference'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioIdRoute = StudioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudioRoute,
} as any)
const StudioVaultRoute = StudioVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => StudioRoute,
} as any)
const VisitReferenceRoute = VisitReferenceRouteImport.update({
  id: '/visit/$reference',
  path: '/visit/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$id': typeof StudioIdRoute
  '/studio/vault': typeof StudioVaultRoute
  '/visit/$reference': typeof VisitReferenceRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/studio/$id': typeof StudioIdRoute
  '/studio/vault': typeof StudioVaultRoute
  '/visit/$reference': typeof VisitReferenceRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$id': typeof StudioIdRoute
  '/studio/vault': typeof StudioVaultRoute
  '/visit/$reference': typeof VisitReferenceRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/login'
    | '/studio'
    | '/studio/$id'
    | '/studio/vault'
    | '/visit/$reference'
    | '/studio/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/login'
    | '/studio/$id'
    | '/studio/vault'
    | '/visit/$reference'
    | '/studio'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/login'
    | '/studio'
    | '/studio/$id'
    | '/studio/vault'
    | '/visit/$reference'
    | '/studio/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  LoginRoute: typeof LoginRoute
  StudioRoute: typeof StudioRouteWithChildren
  VisitReferenceRoute: typeof VisitReferenceRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$id': {
      id: '/studio/$id'
      path: '/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof StudioIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/vault': {
      id: '/studio/vault'
      path: '/vault'
      fullPath: '/studio/vault'
      preLoaderRoute: typeof StudioVaultRouteImport
      parentRoute: typeof StudioRoute
    }
    '/visit/$reference': {
      id: '/visit/$reference'
      path: '/visit/$reference'
      fullPath: '/visit/$reference'
      preLoaderRoute: typeof VisitReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioIdRoute: typeof StudioIdRoute
  StudioVaultRoute: typeof StudioVaultRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioIdRoute: StudioIdRoute,
  StudioVaultRoute: StudioVaultRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  LoginRoute: LoginRoute,
  StudioRoute: StudioRouteWithChildren,
  VisitReferenceRoute: VisitReferenceRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
